# Generated by Django 4.0.3 on 2022-03-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('min_deposit', models.IntegerField()),
                ('max_deposit', models.IntegerField()),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
